/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { LayerMaterial, Color, Texture } from 'lamina';

// import * as LAnkleRoll from './LAnkelRoll.glb';
//import sometjing from '../public/'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/LAnkleRoll.glb')
  console.log("nodes:" , nodes);
  console.log("material:" , materials);

  
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.LAnkleRoll.geometry}  scale={0.01} >
      <LayerMaterial lighting="physical" {...materials.LAnkleRollUV} >
           <Texture map={materials.LAnkleRollUV.map} alpha={1} />
            
          </LayerMaterial>
      </mesh>
    </group>
  )
}

useGLTF.preload('/LAnkleRoll.glb')
